### ISSUE TITLE
rake appcast returns "don't know how to build 'force_build' task"

### ISSUE THREAD

**Issue by jessbowers** [drnic/choctop#1]
when I run the rake appcast command, I get the following:

Don't know how to build task 'force_build'

In looking at choctop.rb, I don't see a tasked called "force_build".

**Comment by jessbowers** [comment]
solution: do not use rake appcast

use rake build or rake dmg instead.

**Comment by drnic** [comment]
Hmm, rake appcast could at least return something pleasant instead.

**Comment by jessbowers** [comment]
I'm using the latest git version, and I don't get this problem.  I think when you release the next gem, it will be solved.  AFIK

**Comment by drnic** [comment]
I've pushed out 0.10.0 so hopefully this issue is resolved now.

**Comment by jessbowers** [comment]
yes, looks fixed to me.
