### ISSUE TITLE
rake dmg creates an empty disk image (doesn't copy files from custom build location)

### ISSUE THREAD

**Issue by billymeltdown** [drnic/choctop#11]
In XCode, under Preferences -> Building, I've got "Place Build Products in" set to Customized location. Most of the current version of choctop, 0.14.1, seems to be cooperating and using this correct location for building the build stage (it's correctly building the app and it's various dependent static libraries there), but when the prepare_files and copy_files steps are run, nothing is copied into build/Release/dmg, and so you end up with an empty (but nice looking) disk image.

I could just copy it in there myself, but it gets cleared out when you run rake dmg anyway. Trying to figure out why it's not working now, but figured I'd give a heads-up, working your way around choctop/dmg.rb can be a little confusing.

**Comment by billymeltdown** [comment]
More info: when I throw a puts at the beginning of DMG::prepare_files, I get something that looks pretty bogus:

```
module ChocTop
  module Dmg
    def prepare_files
      puts "FFFFFFFFFFFFFFFFFFFFILES #{files.inspect}"
      self.files = files.inject({}) do |files, file|
```

Output:

```
FFFFFFFFFFFFFFFFFFFFILES {:target_bundle=>{:position=>[100, 200]}}
```

The rest of the `dmg` task looks like it's working just fine, but nothing gets copied into build/Release/dmg, and I'm not sure why, but it looks a lot like the prepare_files step is working with bad data, since the files array doesn't actually list any of the files to copy.

**Comment by billymeltdown** [comment]
Ah ha, as it turns out I had a few things biting me: not just the custom build products dir but the target name not matching the project name, etc etc. I needed all three of these guys in my Rakefile to get choctop to cooperate (and boy would it have been helpful if I could have gleaned this info from the README instead of debugging the gem libs! :-D )

```
# customize build
s.name = 'My App'
s.build_target = 'MyApp'
s.build_products = '/Users/wgray/Documents/Sources/xcode-build/Release'
```

**Comment by drnic** [comment]
I am glad you survived the debugging process! I'm sorry if some things should be in the README but are not. I did try to document the available variables in the source as best I could; I knew they were going to be important.

It's also tough when I'm a user of the default values - I don't know how other people use choctop :)

Can I ask a favour and you add a little documentation or examples into the README?
Nic

**Comment by billymeltdown** [comment]
Sure thing, I shouldn't be whining anyway, it's a very nice piece of software that's taking care of a lot of business for me, will do.

**Comment by billymeltdown** [comment]
While I've got your ear -- code signing! I just threw in my own whack little task for it, but I think something simple like this could work if you'd be up for bringing it back:

```
task 'codesign' do
  sh "codesign -v -s '#{codesign_identity}' '#{build_products}/#{name}.app'"
  sh "codesign -dv '#{build_products}/#{name}.app'"
end
```

**Comment by drnic** [comment]
You can create new tickets and still have my ear :)
