### ISSUE TITLE
Unavailble rake version in Gemfile.lock

### ISSUE THREAD

**Issue by johnbender** [drnic/choctop#17]
https://github.com/drnic/choctop/blob/master/Gemfile.lock#L27

I'm loath to regenerate the Gemfile.lock having not worked on the project, otherwise I would submit a pull request.

**Comment by drnic** [comment]
Yeah I think I was playing with an in-development version of rake at the time.

```
bundle update rake
```

Committed. I'll let you know when i have the specs running myself. 

## 

Dr Nic Williams
Engine Yard, VP Technology
Silicon Valley Ruby Club, President
http://engineyard.com
http://drnicwilliams.com
cell +1 (415) 860-2185

**Comment by drnic** [comment]
Resolved
