### ISSUE TITLE
Using non-standard build locations is not supported

### ISSUE THREAD

**Issue by jessbowers** [drnic/choctop#2]
Solution: change project settings to use the default (project directory) build location.

**Comment by drnic** [comment]
Can the build location be discovered by choctop? or should it be a configurable option?

**Comment by jessbowers** [comment]
yes, it should be readable via the info.plist.   I'll look into this further when I get a sec.

**Comment by amrox** [comment]
Ideally, it would read the BUILT_PRODUCTS_DIR environment variable that is set by xcodebuild and use that isn't available unless you're running as a script from inside Xcode.

**Comment by drnic** [comment]
Added source_dir to 0.11.1 which defaults to build/Release. Is that what you need?
