### ISSUE TITLE
When folder name of project doesn't match executable, DMG fails

### ISSUE THREAD

**Issue by jessbowers** [drnic/choctop#3]
create xcode project Foo
rename enclosing folder "Bar"
cd to "Bar"
run install_choctop .
rake dmg

hdiutil create -format UDRW -quiet -volname 'Bar' -srcfolder 'build/Release/Bar.app' 'appcast/build/Bar-1.0.dmg'

However, the executable is named "Foo.app"

**Comment by jessbowers** [comment]
Workaround in the Rakefile:

Add an explicit assignment of name:

ChocTop.new do |s|

  s.name = "Foo"

end

**Comment by drnic** [comment]
Do you think this is ok solution/resolution? Or should the default name be based on the contents of the build/Releases/ folder?

We need to explore how choctop can package and deploy non-applications as well; that may guide some of these decisions.

**Comment by jessbowers** [comment]
Well.... that's a different direction entirely - going for other deployments.  

For XCode, there are keys in the configuration files (info.plist, etc) that should be read to determine the settings.  Right now Choctop assumes things based on convention.  However, XCode users can customize the build beyond the default settings, which then breaks Choctop.

I think the workaround is ok for now, but I'd be happy to look into a more permanent fix at a later date (when I'm not so dang busy!!)
