### ISSUE TITLE
The applications alias doesn't work when creating dmgs on non-english systems

### ISSUE THREAD

**Issue by rhult** [drnic/choctop#4]
The alias gets set up as the translated folder name (in my case the Swedish "Program") so the script subsequently fails to position the item (as it's not named "Applications"). A simpler, but still working way would be to replace the applescript code in configure_applications_icon with:

  do shell script "ln -s /Applications /Volumes/#{name}/"

**Comment by rhult** [comment]
Oh, I forgot to say thanks for a great script! :)

**Comment by drnic** [comment]
I think I've pulled in some patches that might fix this now. Can you check 0.11.1 against your bug?

**Comment by drnic** [comment]
closing
